"""Initial migration

Revision ID: 76cb3e62840f
Revises: 
Create Date: 2026-02-15 12:15:33.215523+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76cb3e62840f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('github_id', sa.Integer(), nullable=False),
    sa.Column('github_username', sa.String(length=255), nullable=False),
    sa.Column('github_email', sa.String(length=255), nullable=True),
    sa.Column('github_avatar_url', sa.String(length=512), nullable=True),
    sa.Column('github_access_token', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_github_id'), 'users', ['github_id'], unique=True)
    op.create_index(op.f('ix_users_github_username'), 'users', ['github_username'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('github_repo_id', sa.Integer(), nullable=False),
    sa.Column('github_repo_name', sa.String(length=255), nullable=False),
    sa.Column('github_repo_url', sa.String(length=512), nullable=False),
    sa.Column('default_branch', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('build_command', sa.String(length=512), nullable=True),
    sa.Column('install_command', sa.String(length=512), nullable=True),
    sa.Column('output_directory', sa.String(length=255), nullable=True),
    sa.Column('node_version', sa.String(length=20), nullable=True),
    sa.Column('oss_path', sa.String(length=512), nullable=True),
    sa.Column('default_domain', sa.String(length=255), nullable=True),
    sa.Column('webhook_id', sa.Integer(), nullable=True),
    sa.Column('webhook_secret', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_github_repo_id'), 'projects', ['github_repo_id'], unique=False)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=True)
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_table('build_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('oss_cache_path', sa.String(length=512), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_build_cache_cache_key'), 'build_cache', ['cache_key'], unique=False)
    op.create_index(op.f('ix_build_cache_id'), 'build_cache', ['id'], unique=False)
    op.create_index(op.f('ix_build_cache_project_id'), 'build_cache', ['project_id'], unique=False)
    op.create_table('custom_domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_token', sa.String(length=255), nullable=True),
    sa.Column('ssl_status', sa.Enum('PENDING', 'VERIFYING', 'ISSUING', 'ACTIVE', 'FAILED', 'EXPIRED', name='sslstatus'), nullable=False),
    sa.Column('ssl_certificate_id', sa.String(length=255), nullable=True),
    sa.Column('ssl_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_domains_domain'), 'custom_domains', ['domain'], unique=True)
    op.create_index(op.f('ix_custom_domains_id'), 'custom_domains', ['id'], unique=False)
    op.create_index(op.f('ix_custom_domains_project_id'), 'custom_domains', ['project_id'], unique=False)
    op.create_table('deployments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('commit_sha', sa.String(length=40), nullable=False),
    sa.Column('commit_message', sa.Text(), nullable=True),
    sa.Column('commit_author', sa.String(length=255), nullable=True),
    sa.Column('branch', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'CLONING', 'BUILDING', 'UPLOADING', 'DEPLOYED', 'FAILED', 'CANCELLED', name='deploymentstatus'), nullable=False),
    sa.Column('build_logs', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('oss_url', sa.String(length=512), nullable=True),
    sa.Column('cdn_url', sa.String(length=512), nullable=True),
    sa.Column('deployment_url', sa.String(length=512), nullable=True),
    sa.Column('build_time_seconds', sa.Integer(), nullable=True),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deployed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployments_celery_task_id'), 'deployments', ['celery_task_id'], unique=False)
    op.create_index(op.f('ix_deployments_commit_sha'), 'deployments', ['commit_sha'], unique=False)
    op.create_index(op.f('ix_deployments_id'), 'deployments', ['id'], unique=False)
    op.create_index(op.f('ix_deployments_project_id'), 'deployments', ['project_id'], unique=False)
    op.create_index(op.f('ix_deployments_status'), 'deployments', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deployments_status'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_project_id'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_id'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_commit_sha'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_celery_task_id'), table_name='deployments')
    op.drop_table('deployments')
    op.drop_index(op.f('ix_custom_domains_project_id'), table_name='custom_domains')
    op.drop_index(op.f('ix_custom_domains_id'), table_name='custom_domains')
    op.drop_index(op.f('ix_custom_domains_domain'), table_name='custom_domains')
    op.drop_table('custom_domains')
    op.drop_index(op.f('ix_build_cache_project_id'), table_name='build_cache')
    op.drop_index(op.f('ix_build_cache_id'), table_name='build_cache')
    op.drop_index(op.f('ix_build_cache_cache_key'), table_name='build_cache')
    op.drop_table('build_cache')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_github_repo_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_github_username'), table_name='users')
    op.drop_index(op.f('ix_users_github_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
